# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              kabayankababayan
author:             Sahri Riza Umami
email:              riza@openmailbox.org
description:        'Blog about things me think is interesting.'
# the subpath of your site, e.g. /blog
baseurl:            ''
permalink:          pretty
# the base hostname & protocol for your site
url:                https://rizaumami.github.io 
github_username:    rizaumami
telegram_username:  kuncen
disqus_username:    rizaumami

# Build settings
markdown:           kramdown

gems:
  - jemoji
